name: sindy_pi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyter
  - pip
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter_client
  - jupyter_core
  - jupyterlab_widgets
  - matplotlib
  - seaborn
  - numpy
  - pandas
  - sympy
  - scipy
  - scikit-learn
  - python-graphviz
  - psutil
  - tqdm
  - tk
  - traitlets
  - typing_extensions
  - tornado
  - setuptools
  - sqlite
  - zlib
  - wheel
  - pygments
  - platformdirs
  - packaging
  - prompt-toolkit
  - wcwidth
  - parso
  - nest-asyncio
  - debugpy
  - matplotlib-inline
  - zeromq
  - pyzmq
  - six
  - python-dateutil
  - stack_data
  - pure_eval
  - pexpect
  - ptyprocess
  - comm
  - exceptiongroup
  - executing
  - jedi
  - pip:
      - attrs==25.3.0
      - clarabel==0.10.0
      - cmake==4.0.0
      - contourpy==1.3.2
      - cvxpy==1.6.5
      - cycler==0.12.1
      - derivative==0.6.3
      - fastjsonschema==2.21.1
      - fonttools==4.57.0
      - importlib-metadata==8.6.1
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - scikit-image
      - mpmath==1.3.0
      - narwhals==1.35.0
      - nbformat==5.10.4
      - numpy==1.23.5
      - osqp==1.0.3
      - pandas==2.2.3
      - pillow==11.2.1
      - plotly==6.0.1
      - pyparsing==3.2.3
      - pysindy==1.7.5
      - pytz==2025.2
      - referencing==0.36.2
      - rpds-py==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - scs==3.2.7.post2
      - seaborn==0.13.2
      - sympy==1.13.3
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - tqdm-joblib==0.0.4
      - tzdata==2025.2
      - zipp==3.21.0
      - pytisean==0.1.1
      - importlib-resources==6.5.2
